// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6OdeGec5s2CW14-VSFkopCqv7CsI3fv4',
    appId: '1:55884219577:android:4bb4dd1ce12ce18a190768',
    messagingSenderId: '55884219577',
    projectId: 'dalel-fd27c',
    storageBucket: 'dalel-fd27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHY7q02zMG5Retw6QK7IxD6zIzdXOrFE',
    appId: '1:55884219577:ios:a8bd5b0d3b76f664190768',
    messagingSenderId: '55884219577',
    projectId: 'dalel-fd27c',
    storageBucket: 'dalel-fd27c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
